#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#        default-filters:
#          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#             - POST
#             - GET
#             - OPTIONS
#            allowedHeaders: "*"
#            allowCredentials: false